services:
  postgres:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: on-failure
    command: bash -c "alembic upgrade head && python3 -m src.main" 
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env 
    volumes:
      - .:/app

volumes:
  postgres_data: